### ISSUE TITLE
Reference to BeginPlay

### ISSUE THREAD

**Issue by KitsuneDev** [TeamCyberless/DiscordGameSDK#4]
Commit [11babc2](https://github.com/TeamCyberless/DiscordGameSDK/commit/11babc26fd31fc5e8dd47e83ab525c7aaf147b87) removes `UDiscordCore::BeginPlay`, but there is still a reference to it at [DiscordCore.cpp#46](https://github.com/TeamCyberless/DiscordGameSDK/blob/11babc26fd31fc5e8dd47e83ab525c7aaf147b87/Source/DiscordGSDK/Private/DiscordCore.cpp#L46), thus blocking the plugin's compilation.

**Comment by Eletmetrix** [comment]
The problem mentioned in the issue has been fixed in the latest update. Thank you for bringing this to our attention and please feel free to reach out if you encounter any further issues or have any other feedback.

Happy coding!
